export const WORKDAY_PAGES = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  RESUME: "RESUME",
  PERSONAL_DETAILS: "PERSONAL_DETAILS",
  EXPERIENCE_DETAILS: "EXPERIENCE_DETAILS",
  APPLICATION_QUESTIONS: "APPLICATION_QUESTIONS",
} as const;
