import path from 'path';

export const isMocked = ''; // "workday";

export const TIMEOUTS = {
  CLICK: { timeout: 300 },
  FIND: { timeout: 500 },
  PAGE_START_SHORT: { timeout: 1500 },
  PAGE_START: { timeout: 3500 },
  EXTENDED_TIME: { timeout: 8000 },
};

export const FORM_FIELDS = {
  PERSONAL_DETAILS: {
    FIRST_NAME: 'Sathyanarayanan',
    LAST_NAME: 'S',
    PHONE_NUMBER: '4106007266',
    PHONE_CODE: '+1',
    EMAIL: 'sathy.sunder@gmail.com', //"sathy.sunder@gmail.com", "soms.sathya@gmail.com",
    LINKEDIN: 'https://www.linkedin.com/in/sathya-s96',
    RESUME: path.join(__dirname, '../assets/resume.docx'),
    EXPERIENCES: path.join(__dirname, '../assets/experience.docx'),
    LOGIN: {
      USERNAME: 'zathya1990',
      PASSWORD: 'Shreeni@19Zxsa@1990',
      SECONDARY_PASSWORD: 'Zxsa@1990',
    },
    ADDRESS: {
      FIRST_LINE: '1644 Gleneagle Rd',
      ZIP: '21239',
      STATE: 'Maryland',
      CITY: 'Baltimore',
      COUNTRY: 'United States',
      STATE_SHORT: 'MD',
      COUNTRY_SHORT: 'US',
    },
  },
  COLLEGES: {
    MASTERS: {
      NAME: 'New Jersey Institute Of Technology',
      MAJOR: 'Computer Science',
      LOCATION: {
        CITY: 'Newark',
        STATE: 'New Jersey',
        COUNTRY: 'United States',
      },
    },
    BACHELORS: {
      NAME: 'SRM Institute of Science and Technology',
      MAJOR: 'Electronics and Communication Engineering',
      LOCATION: {
        CITY: 'Chennai',
        STATE: 'Tamil Nadu',
        COUNTRY: 'India',
      },
    },
  },
  EXPERIENCES: {
    AMERIPRISE: {
      COMPANY: 'Ameriprise Financial',
      TITLE: 'Senior/Lead Frontend Engineer',
      START_DATE: '2023-03',
      END_DATE: 'Present',
      IS_CURRENT: true,
      LOCATION: {
        CITY: 'Minneapolis',
        STATE: 'Minnesota',
        COUNTRY: 'United States',
      },
      RESPONSIBILITIES: [
        'Spearheaded development of a high-traffic financial application using ReactJS, NodeJS, Java, JavaScript, and TypeScript.',
        'Led site-wide migration to Micro Frontends (MFE) and SPA redesign, optimizing scalability with Webpack bundle, React lazy-loading, and memoization.',
        'Built a standardized UI component library leveraging Storybook, HTML5, SCSS, Tailwind CSS, Material UI, and JavaScript tooling.',
        'Enhanced frontend performance via client-side REST API caching with Redux and React Context.',
        'Collaborated with design and content teams to translate Figma features into responsive, pixel-perfect React components.',
        'Maintained CI/CD pipelines and planned A/B testing production release strategy in Kubernetes (AWS EKS) and Docker; monitored releases in GlassBox.',
        'Increased site engagement by 45% and conversion rate by 24%.',
        'Improved Lighthouse performance scores and overall UX through MFE and SPA optimizations.',
        'Raised WCAG/ARIA accessibility scores to 98% with the standardized component library.',
        'Reduced time-to-interaction through client-side caching strategies.',
      ],
      COMPANY_WEBSITE: 'https://www.ameriprise.com',
    },
    NORTHWESTERN: {
      COMPANY: 'Northwestern Mutual',
      TITLE: 'Senior Frontend Engineer',
      START_DATE: '2022-05',
      END_DATE: '2023-12',
      IS_CURRENT: false,
      LOCATION: {
        CITY: 'Milwaukee',
        STATE: 'Wisconsin',
        COUNTRY: 'United States',
      },
      RESPONSIBILITIES: [
        'Led development to convert a large-scale distributed insurance application to Micro Frontend (MFE) using ReactJS, NodeJS, Java, GraphQL, and AWS.',
        'Maintained insurance products and set up MFE repositories using Webpack, Babel, URQL, Redux and React Context.',
        'Implemented scalable PDF generation and data visualizations using custom component library and d3.js.',
        'Developed and deployed Java and Node (TypeScript) microservices in Kubernetes and set up CI/CD in AWS/S3.',
        'Implemented end-to-end and unit testing with Cypress, Playwright, Enzyme and Jest; mentored junior engineers.',
        'Reduced refresh times by 30%.',
        'Improved frontend download and rendering performance for PDFs and graphs.',
        'Increased test coverage and code quality via automated regression and unit testing.',
      ],
      COMPANY_WEBSITE: 'https://www.northwesternmutual.com',
    },
    ENVOGUE: {
      COMPANY: 'Envogue International',
      TITLE: 'Founding Frontend Engineer',
      START_DATE: '2021-01',
      END_DATE: '2022-12',
      IS_CURRENT: false,
      LOCATION: {
        CITY: 'New York',
        STATE: 'New York',
        COUNTRY: 'United States',
      },
      RESPONSIBILITIES: [
        'Led development of a B2B ecommerce application to production using React, React Native, Python, Java, AWS, Docker and Kubernetes.',
        'Built WCAG-compliant responsive React/Redux interfaces with Material UI for content management.',
        'Developed dynamic UI with Context API, global CSS animations, and responsive layouts.',
        'Scaled and secured Python GraphQL backend with SSO/OAuth, implemented CI/CD and monitoring in CloudWatch.',
        'Launched B2B ecommerce product and improved accessibility by 40% while reducing user task time by 30%.',
      ],
      COMPANY_WEBSITE: '',
    },
    NJIT: {
      COMPANY: 'New Jersey Institute of Technology',
      TITLE: 'Research Assistant – Data Scientist',
      START_DATE: '2019-10',
      END_DATE: '2021-06',
      IS_CURRENT: false,
      LOCATION: {
        CITY: 'Newark',
        STATE: 'New Jersey',
        COUNTRY: 'United States',
      },
      RESPONSIBILITIES: [
        'Developed a data visualization tree using ReactJS, NodeJS, Docker, Kubernetes, and d3.js for exploration of multidimensional data.',
        'Implemented parallel computing using Python, NumPy, and CUDA.',
        'Engineered multi-agent reinforcement learning models and integrated deep learning models using TensorFlow.',
        'Developed CNN, RNN, NLP, OCR, and segmentation models with TensorFlow, Keras, and PyTorch leveraging CUDA.',
        'Delivered interactive visualization tools and performant ML pipelines for research experiments.',
      ],
      COMPANY_WEBSITE: 'https://www.njit.edu',
    },
    ARCHEAN: {
      COMPANY: 'Archean MyCity Social Network',
      TITLE: 'Software Engineer',
      START_DATE: '2018-01',
      END_DATE: '2019-12',
      IS_CURRENT: false,
      LOCATION: {
        CITY: 'Chennai',
        STATE: 'Tamil Nadu',
        COUNTRY: 'India',
      },
      RESPONSIBILITIES: [
        'Led development of a social media application to production using React, React Native, and Google Cloud.',
        'Delivered production-ready social media app and integrations on Google Cloud.',
      ],
      COMPANY_WEBSITE: '',
    },
  },
  APPLICATION_FIELDS: {
    SALARY_TYPE: 'Negotiable',
    LINKEDIN_LABEL: 'LinkedIn',
    EXPECTED_SALARY: '120000',
    RELOCATION: 'Open to relocate anywhere in the US',
    IMMIGRATION_STATUS: 'Currently on H1B with my employer.',
  },
  JOB_TITLES: {
    SENIOR: 'Senior Software Engineer',
    DEFAULT: 'Software Engineer',
  },
  AVAILABILITY: {
    IMMEDIATELY: 'Immediately',
    NA: 'N/A',
  },
  RATES: {
    YEARLY: '96,000$/Year',
    HOURLY: '48$/Hour',
  },
  DM_TEMPLATES: {
    SHORT:
      'Hi, I came across your Software Engineer post. If you know about this role I was wondering if you can give me a referral or view my resume for the role? Please let me know. Thank you for your time.',
    LONG: 'Hi, \nI came across a Software Engineer post. If you know about this role I was wondering if you could give me a referral or view my resume for the role? Please let me know. Or we could connect and talk about my cute puppy. Thank you for your time.',
  },
  SKILLS: [
    'React',
    'Angular',
    'Node.js',
    'Spring Boot',
    'JavaScript',
    'TypeScript',
    'ECMAScript',
    'JSON',
    'CSS',
    'SASS',
    'HTML',
    'XML',
    'Python',
    'SQL',
    'PostgreSQL',
    'MongoDB',
    'Webpack',
    'Tailwind',
    'Material UI',
    'Redux',
    'Amazon Web Services',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Git',
    'SDLC',
    'Jest',
    'Playwright',
    'React Testing Library',
    'Lighthouse',
    'GenAI Copilot',
    'Chrome Dev Tools',
  ],
};

export const SNIPPETS: Record<string, string> = {
  // Personal
  ss: `${FORM_FIELDS.PERSONAL_DETAILS.FIRST_NAME} ${FORM_FIELDS.PERSONAL_DETAILS.LAST_NAME}`,
  sa: FORM_FIELDS.PERSONAL_DETAILS.FIRST_NAME,
  sm: 'Somasunder',
  sh: 'Shreenidark@1990',
  Zx: FORM_FIELDS.PERSONAL_DETAILS.LOGIN.SECONDARY_PASSWORD,
  cv: 'Cvfd1880@',
  zat: FORM_FIELDS.PERSONAL_DETAILS.LOGIN.USERNAME,
  em: FORM_FIELDS.PERSONAL_DETAILS.EMAIL,
  ln: FORM_FIELDS.PERSONAL_DETAILS.LINKEDIN,
  ll: FORM_FIELDS.APPLICATION_FIELDS.LINKEDIN_LABEL,
  '97': FORM_FIELDS.PERSONAL_DETAILS.PHONE_NUMBER,

  // Address
  '16': FORM_FIELDS.PERSONAL_DETAILS.ADDRESS.FIRST_LINE,
  '21': FORM_FIELDS.PERSONAL_DETAILS.ADDRESS.ZIP,
  md: FORM_FIELDS.PERSONAL_DETAILS.ADDRESS.STATE,
  ba: FORM_FIELDS.PERSONAL_DETAILS.ADDRESS.CITY,
  us: FORM_FIELDS.PERSONAL_DETAILS.ADDRESS.COUNTRY,

  // Education
  njit: FORM_FIELDS.COLLEGES.MASTERS.NAME,
  srm: FORM_FIELDS.COLLEGES.BACHELORS.NAME,
  cs: FORM_FIELDS.COLLEGES.MASTERS.MAJOR,
  ee: FORM_FIELDS.COLLEGES.BACHELORS.MAJOR,

  // Companies
  am: FORM_FIELDS.EXPERIENCES.AMERIPRISE.COMPANY,
  nm: FORM_FIELDS.EXPERIENCES.NORTHWESTERN.COMPANY,
  ae: 'Aekya Inc',
  en: 'Envogue',

  // Job / application
  sse: FORM_FIELDS.JOB_TITLES.SENIOR,
  se: FORM_FIELDS.JOB_TITLES.DEFAULT,
  ng: FORM_FIELDS.APPLICATION_FIELDS.SALARY_TYPE,
  rl: FORM_FIELDS.APPLICATION_FIELDS.RELOCATION,
  h1: FORM_FIELDS.APPLICATION_FIELDS.IMMIGRATION_STATUS,
  '12': FORM_FIELDS.APPLICATION_FIELDS.EXPECTED_SALARY,
  '96': FORM_FIELDS.RATES.YEARLY,
  '48': FORM_FIELDS.RATES.HOURLY,
  im: FORM_FIELDS.AVAILABILITY.IMMEDIATELY,
  na: FORM_FIELDS.AVAILABILITY.NA,

  // Long text
  nje: 'Developed a data visualization tree using ReactJS, NodeJS, Docker, Kubernetes, and d3.js for intuitive exploration of multidimensional data. Implemented parallel computing using Python, Numpy, and CUDA, \nEngineered a multi-agent reinforced learning model simulating naval ships and integrated deep learning models on TensorFlow. \nDeveloped Convolutional Neural Networks (CNN), Recurrent Neural Networks (RNN), Natural Language Processing (NLP), Optical Character Recognition (OCR), and Segmentation models on TensorFlow, Keras, and PyTorch, leveraging CUDA for enhanced computational efficiency.',
  are: '• Developed a data visualization tree using ReactJS, NodeJS, Docker, Kubernetes, and d3.js for intuitive exploration of multidimensional data. Implemented parallel computing using Python, Numpy, and CUDA, \n• Engineered a multi-agent reinforced learning model simulating naval ships and integrated deep learning models on TensorFlow. \n• Developed Convolutional Neural Networks (CNN), Recurrent Natural Networks (RNN), Natural Language Processing (NLP), Optical Character Recognition (OCR), and Segmentation models on TensorFlow, Keras, and PyTorch, leveraging CUDA for enhanced computational efficiency.',
  txt: FORM_FIELDS.DM_TEMPLATES.SHORT,
  cte: FORM_FIELDS.DM_TEMPLATES.LONG,
};
